language: scala
scala:
  - 2.13.0
  - 2.12.8
  - 2.11.12
  - 2.10.7

jdk:
  - oraclejdk8
script: |
  if [[ "$TRAVIS_SCALA_VERSION" == 2.13.* ]]; then
    sbt ++$TRAVIS_SCALA_VERSION clean coverage test
  else
    sbt ++$TRAVIS_SCALA_VERSION clean test
  fi
after_success: |
  if [[ "$TRAVIS_SCALA_VERSION" == 2.13.* ]]; then
    sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls
  fi
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
